### ISSUE TITLE
A non correct double-tap-drag-zoom gesture freeze map

### ISSUE THREAD

**Issue by wiwari** [cherniavskii/Leaflet.DoubleTapDragZoom#12]
A non finished double-tap-drag-zoom: "A tap following pinch action" will cause freezing in 0.3.0.
It seems drag and zoom events not propagating.
The abnormal state can be recovered back to normal by triggering another double tap drag zoom action.

The case is only found in 0.3.0 but 0.2.0

**Comment by zta6** [comment]
We're experiencing this issue as well. At a glance I'd guess the problem came from : 512b096bcbfd033f49cf283241eb407302a0ab46

I think there are some instances where `this._doubleTapDragging` needs to get set back to false but doesn't.

**Comment by chnuessli** [comment]
I am experiencing this issue as well. Can you merge #13 to testify if this is working?

**Comment by cherniavskii** [comment]
Closed by https://github.com/cherniavskii/Leaflet.DoubleTapDragZoom/pull/13

**Comment by cherniavskii** [comment]
Released in https://github.com/cherniavskii/Leaflet.DoubleTapDragZoom/releases/tag/0.3.1
